### PR TITLE
Enumerables Project

### PR DESCRIPTION
**Pull request by yahir91**
> In this project, we implemented our version of Ruby’s enumerable methods:
>- #each
>- #each_with_index
>- #all?
>- #select
>- #any?
>- #none?
>- #count
>- #map
>- #inject

### CODE REVIEW

**Review by serdg0 — CHANGES_REQUESTED** [review]
### Hi @MarilenaRoque @yahir91 ! :peace_symbol: 

You've done a great job guys! **Congratulations!**
Although there are some cases that we need to consider before we can approve this project!

- [x] Consider when a **range** is passed in the following methods:


my_each
my_each_with_index
my_select
my_all
my_any
my_none
my_count
my_map

- [x] Consider when a hash is passed to my_each, my_each_with_index


- [x] my_each_with_index is returning a single integer. When tested with a block, it should return the array itself with the block called to each of its elements.


- [x] my_none should return true, when passed a block, if none of it's elements return true.


- [x] my_inject should raise a "LocalJumpError" when no block or argument is given. [Here](https://airbrake.io/blog/ruby-exception-handling/localjumperror) is a little text about this error that I hope it helps you handling this. 


- [x] Create a method called multiply_els for testing my_inject (screenshot from pathwright):




Address those issues and submit for another CRR.

Keep the good work and...
### **Happy Coding!** :computer: :nerd_face:
**_Sergio Diaz_**

**Comment by MarilenaRoque** [comment]
Hey @serdg0, I am happy to say that we've worked in all the issues noticed, and everything is solved. :rocket:

- [x]  Consider when a range is passed in the following methods:
- [x] Consider when a hash is passed to my_each, my_each_with_index
- [x] my_each_with_index is returning a single integer. When tested with a block, it should return the array itself with the block called to each of its elements.
- [x] my_none should return true, when passed a block, if none of it's elements return true.
- [x] my_inject should raise a "LocalJumpError" when no block or argument is given. Here is a little text about this error that I hope it helps you handling this.
- [x] Create a method called multiply_els for testing my_inject

Thank you for your awesome and comprehensive review! :smiley:

**Review by MarioDena — APPROVED** [review]
Hello Team! 

Awesome job implementing the requested changes! 🏅 

Project approved! 

Good luck on the next one! 🦾

**Comment by MarilenaRoque** [comment]
Thank you so much for the review @MarioDena! :rocket:

**Pull request merged**
